# requires the following secrets:
# DT_BASE_URL
# DT_API_TOKEN 

name: Demo Deployment
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
      
    - name: "Build Code"
      run: |
        echo "Building Code"

    - name: "Deploy Code"
      run: |
        echo "Deploying Code"

    - name: Dynatrace Deployment Event
      uses: dynatrace-oss/dynatrace-github-action@v9
      with:
        url: '${{ secrets.DT_BASE_URL }}'
        token: '${{ secrets.DT_API_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            title: Simulated Deployment
            entitySelector: type(SERVICE),tag(keptn_project:release-demo),tag(keptn_service:casdemoapp),tag(keptn_stage:production)
            properties:
              source: GitHub
              deploymentName: "GitHub Action"
              deploymentVersion: "${{ github.ref }}"
              deploymentProject: "${{ github.repository }}"
              remediationAction: "None"
              ciBackLink: "https://github.com/${{ github.repository }}"
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
              owner: demo-user
          
